name: talk_to_pdf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit==1.49.1
    - numpy==2.3.2
    - requests==2.32.5
    - python-dotenv==1.0.1
    - sqlalchemy==2.0.27
    - pdfminer.six==20231228
    - streamlit-lottie==0.0.5
    - psycopg2-binary==2.9.9
    - mistralai==0.4.2