# .streamlit/secrets.toml

# Mistral API Key (Free tier: 1M tokens/month)
MISTRAL_API_KEY = "66AjJXFO1UquZtg1bPue1pS8MyU3pvzd"

# Supabase PostgreSQL URL
SUPABASE_POSTGRES_URL = "postgresql://postgres:IAMkeshav1.@db.ajhvffcjzewqkugdocnh.supabase.co:5432/postgres"

# Google Service Account Credentials
[google_credentials]
type = "service_account"
project_id = "final-rag-bot"
private_key_id = "1ead5101e2cc649c96c4e5e3b96a44a752884fe6"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCdqXwWGjVeCOQ6
Ksfpqpbbtj3wuX8g75FRjKwUU+H5AS51fcYlV7xRDWNCg/DB1xjvOIMU7aC2s51b
Zl3kJhjUaHAETIum7oBgmNt9J4xAbJ/HjUTuwy/15QTPONhanL53I7kRmYodh2Yy
V6RhVgZdqGcyUgYYUaNw9lU2VTF7V4+h4caiiuTxSPQk+vtEAWETuX7Gy3jH+c0J
G2WwEqTF5TIgtcBE44Zb9vh0bNSR9zW/N1kDpdBz+bD2caH+m864/bFIxRfBdAR6
bFuOLa26TtDiaAZrJoNc8oGrxxlR00thJSC+b+DYWUrk0oyfU1MfbT7MNNL82vKc
rv323n6pAgMBAAECggEABfstSjBd2G6pa9x+H4r5dKXeBTEgVclI38lgqNfC0Z2+
G7Z1CysgKYoCuz4CpvPoTgD8lhFqwKuhO1uvka1xUTOSFlOqE5/mLmP2JbIXo8UL
LbiaBh3RBrjUvSDIsm1SW3Y3OefzganGkn/ZLFklXi26loHemdMVCn7J3kkOmsF5
GxiW0ZnRc+4E1aX5LNAjIoKovqMJhAzbw2rURa+4WGrbmuUihZzYjDu9sM3viMl0
Qw/rfKHrlSsLw4qtnoHgVvvEtGe+b/kQoztdjrgUD8oWGxLUUMLMgQjtwNtZa2gm
vpvHvT6HhwhCZGDTSGPFebsIEssjZ7VPlAPdJyNhtQKBgQDWDVOOXECOQCq70pFT
EdfrnvpY0BgOQr0L8ELfFyKRXEnOcODPignGZ3UA1X1wFCPHu/cdWnCSeH6ZVaFL
f17s7I6To2qaS1+I9+/yXDhZBf9BbeQEIvfeHKZNIfBdwzOqd7LxsjY3A97AXnSp
tnYVUogoxnY2GNSs0CBMtnI2pQKBgQC8jyfNh8nh9DqwT9u8c2kSVfSJKr890vbO
0I3N384ekfl/kI6LsccE6Jxv+9lmbMlBvEnUYV9vp4zPO9x/QKkW8ZFo8qkllToh
ib6qamVHIFvS/A0/qpSbOqQ2NT3MmPBJfhNKTjmITuBHlSVQxz16MJ303AwTFgs8
rcAtGBustQKBgAno0Ad1Kd/sBI5xbxzjZJWZ5IkcCSEP4eSdmNrvHUCRfzE5dI7n
GxC+VWJWf9oidI2YnBYVy8RcI7BBkJgIK4LYaLlZBWRjPOcAY3Fa55jneCu1RKsU
W1lDBkfn3FLa6JdptzUNRQlC+pr5RHle4xSVn4wTtAFJIP9nGzex8pOpAoGAO21m
3wkP4I3nvU+98lvxXp0GkACP+3002iOyvZLu1IWvO7wkoPRrxClHvKeEchqRJ42f
OzdhK8CDyYCVUunfIOMLsCbilny8sHtIQ097Efqp1gooZsttQKsvvAH1szj0akU4
8S9MRKCPYSApfZb90jfmYJjFmXJWIk6khdHWTw0CgYAEGEo246YkgKQ/UcT39wxQ
YsCLuWM/rLfgKwWpq+5oEG4eUT+xwQR4HkEV3Q4Dwy/08RRg5s6jJ9NPdrsrDJ7W
q69lL53ZXEZLCe4rpQ/n7iVPGa7gliFgw1sLBZN2Dxjy8We0XSGfiVfILNkxvBxk
lC0frQ9voAGlitNFQuheCQ==
-----END PRIVATE KEY-----
"""
client_email = "keshav-agarwal@final-rag-bot.iam.gserviceaccount.com"
client_id = "118051226548670134205"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/keshav-agarwal%40final-rag-bot.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
